name: Python application

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKEB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        docker image build -t dab8106/gitaction:v1 .
        docker push dab8106/gitaction:v1
