name: docker image CI
on:
 push:
    branches: [ master]
 pull_request:
   branches: [ master ]
jobs:
  push_to_registries:
   name: push Docker image to multiple registries
   runs-on: ubuntu-latest
   steps:
     - name: check the repo
       uses: actions/cgeckout@v2
     - name: Build and publish head Docker image
       uses: VaultVulp/gp-docker-action@1.1.7
       with:
         github-token: $ {{ secrets.TOKEN }} 
         image-name: myapp
         image-tag: v1
